### ISSUE TITLE
More settings to customize ACE

### ISSUE THREAD

**Issue by legionus** [kud/firefox-simple-text-editor#12]
ACE.js have a many settings such as Mode, Font Size, etc. Can you add them in addon settings or somewhere else ?

**Comment by kud** [comment]
Yep ;) It's a good idea.

**Comment by legionus** [comment]
Great!
Sorry for offtopic, but do you have any plans to make the ability to save text to a real filesystem ?

**Comment by kud** [comment]
Nope but could also be a good idea ;)

**Comment by legionus** [comment]
Two years ago I tried to start a similar project: https://github.com/legionus/mozeditor. Now he probably  broken, but in it I implemented reading and writing to the local filesystem.

**Comment by kud** [comment]
It seems that my addon is more used by other people than me. :D 

If I have any time, I'll add all your features requested. Sounds good to me.

**Comment by legionus** [comment]
Thanks! :)
